/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.phenotips.remote.api;

/**
 * The functions essential to the servers ability to store, track, an answer search requests.
 */
public interface SearchRequest
{
    /**
     * The id of the other server (for both inocming and outgoing requests)
     *
     * @return
     */
    String getRemoteServerId();

    /**
     * Query ID, as reported to or by external systems and used in modification URLs.
     * Note: generated by remote system for outgoing requests and by this system for incoming requests.
     */
    String getQueryId();

    /**
     * Either "once" or "periodic". Default: "once"
     */
    String getQueryType();

    /**
     * Is not mandatory for {@link org.phenotips.remote.api.OutgoingSearchRequest} as it is instantiated with the
     * default value.
     */
    String getResponseType();

    /**
     * Default: null
     */
    String getSubmitterName();

    /**
     * Default: null
     */
    String getSubmitterEmail();

    /**
     * Default: null
     */
    String getSubmitterInstitution();
}
